/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--primary-50) / <alpha-value>)',
          100: 'rgb(var(--primary-100) / <alpha-value>)',
          200: 'rgb(var(--primary-200) / <alpha-value>)',
          300: 'rgb(var(--primary-300) / <alpha-value>)',
          400: 'rgb(var(--primary-400) / <alpha-value>)',
          500: 'rgb(var(--primary-500) / <alpha-value>)',
          600: 'rgb(var(--primary-600) / <alpha-value>)',
          700: 'rgb(var(--primary-700) / <alpha-value>)',
          800: 'rgb(var(--primary-800) / <alpha-value>)',
          900: 'rgb(var(--primary-900) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        accent: {
          50: 'rgb(var(--accent-50) / <alpha-value>)',
          100: 'rgb(var(--accent-100) / <alpha-value>)',
          200: 'rgb(var(--accent-200) / <alpha-value>)',
          300: 'rgb(var(--accent-300) / <alpha-value>)',
          400: 'rgb(var(--accent-400) / <alpha-value>)',
          500: 'rgb(var(--accent-500) / <alpha-value>)',
          600: 'rgb(var(--accent-600) / <alpha-value>)',
          700: 'rgb(var(--accent-700) / <alpha-value>)',
          800: 'rgb(var(--accent-800) / <alpha-value>)',
          900: 'rgb(var(--accent-900) / <alpha-value>)',
        },
        calm: {
          50: 'rgb(var(--calm-50) / <alpha-value>)',
          100: 'rgb(var(--calm-100) / <alpha-value>)',
          200: 'rgb(var(--calm-200) / <alpha-value>)',
          300: 'rgb(var(--calm-300) / <alpha-value>)',
          400: 'rgb(var(--calm-400) / <alpha-value>)',
          500: 'rgb(var(--calm-500) / <alpha-value>)',
          600: 'rgb(var(--calm-600) / <alpha-value>)',
          700: 'rgb(var(--calm-700) / <alpha-value>)',
          800: 'rgb(var(--calm-800) / <alpha-value>)',
          900: 'rgb(var(--calm-900) / <alpha-value>)',
          950: 'rgb(var(--calm-950) / <alpha-value>)',
        },
        lavender: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        mint: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        emerald: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        green: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        teal: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        cyan: {
          50: 'rgb(var(--cyan-50) / <alpha-value>)',
          100: 'rgb(var(--cyan-100) / <alpha-value>)',
          200: 'rgb(var(--cyan-200) / <alpha-value>)',
          300: 'rgb(var(--cyan-300) / <alpha-value>)',
          400: 'rgb(var(--cyan-400) / <alpha-value>)',
          500: 'rgb(var(--cyan-500) / <alpha-value>)',
          600: 'rgb(var(--cyan-600) / <alpha-value>)',
          700: 'rgb(var(--cyan-700) / <alpha-value>)',
          800: 'rgb(var(--cyan-800) / <alpha-value>)',
          900: 'rgb(var(--cyan-900) / <alpha-value>)',
        },
        coral: {
          50: 'rgb(var(--coral-50) / <alpha-value>)',
          100: 'rgb(var(--coral-100) / <alpha-value>)',
          200: 'rgb(var(--coral-200) / <alpha-value>)',
          300: 'rgb(var(--coral-300) / <alpha-value>)',
          400: 'rgb(var(--coral-400) / <alpha-value>)',
          500: 'rgb(var(--coral-500) / <alpha-value>)',
          600: 'rgb(var(--coral-600) / <alpha-value>)',
          700: 'rgb(var(--coral-700) / <alpha-value>)',
          800: 'rgb(var(--coral-800) / <alpha-value>)',
          900: 'rgb(var(--coral-900) / <alpha-value>)',
        },
        amber: {
          50: 'rgb(var(--amber-50) / <alpha-value>)',
          100: 'rgb(var(--amber-100) / <alpha-value>)',
          200: 'rgb(var(--amber-200) / <alpha-value>)',
          300: 'rgb(var(--amber-300) / <alpha-value>)',
          400: 'rgb(var(--amber-400) / <alpha-value>)',
          500: 'rgb(var(--amber-500) / <alpha-value>)',
          600: 'rgb(var(--amber-600) / <alpha-value>)',
          700: 'rgb(var(--amber-700) / <alpha-value>)',
          800: 'rgb(var(--amber-800) / <alpha-value>)',
          900: 'rgb(var(--amber-900) / <alpha-value>)',
        },
        blue: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
        },

      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Poppins', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      boxShadow: {
        glass: 'var(--box-shadow)',
        glassDark: 'var(--box-shadow)',
        soft: 'var(--box-shadow)',
        glow: '0 0 20px rgba(139, 111, 203, 0.3)',
        glowSm: '0 0 10px rgba(139, 111, 203, 0.2)',
        glowLg: '0 0 40px rgba(139, 111, 203, 0.4)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        pulseSlow: 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        gradient: 'gradient 8s ease infinite',
        shimmer: 'shimmer 2s linear infinite',
        slideUp: 'slideUp 0.5s ease-out',
        slideDown: 'slideDown 0.5s ease-out',
        fadeIn: 'fadeIn 0.5s ease-out',
        scaleIn: 'scaleIn 0.3s ease-out',
        bounceSlow: 'bounce 3s ease-in-out infinite',
        spinSlow: 'spin 3s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backgroundImage: {
        gradientRadial: 'radial-gradient(var(--tw-gradient-stops))',
        gradientConic: 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        glassGradient: 'linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.05))',
        meshGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        calmGradient: 'linear-gradient(135deg, #EDE7F6 0%, #F8F5F2 100%)',
        sunsetGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        oceanGradient: 'linear-gradient(135deg, #DCCEF2 0%, #B8A4D4 100%)',
        forestGradient: 'linear-gradient(135deg, #5A4D7A 0%, #B8A4D4 100%)',
      },
    },
  },
  plugins: [],
};
